name: Makefile CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install software
      run: |
         sudo apt install devscripts debhelper-compat build-essential
    - name: Build
      run: make build

    - name: Retrieve build artifact
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.deb
        token: ${{ secrets.GITHUB_TOKEN }}
